ALTER TABLE "TASK_SUBTASKS"
ADD COLUMN "progressPercent" INTEGER NOT NULL DEFAULT 25;

ALTER TABLE "TASK_SUBTASKS"
ADD CONSTRAINT "TASK_SUBTASKS_progressPercent_check"
CHECK ("progressPercent" IN (25, 50, 75, 100));
