-- Provider trust profile data for individual providers.
CREATE TYPE "CertificateVerificationStatus" AS ENUM ('PENDING', 'VERIFIED', 'REJECTED');

CREATE TABLE "PROVIDER_PROFILES" (
  "id" SERIAL NOT NULL,
  "userId" INTEGER NOT NULL,
  "address" TEXT,
  "district" TEXT,
  "city" TEXT,
  "specialties" TEXT[] DEFAULT ARRAY[]::TEXT[],
  "safetyComplianceAgreed" BOOLEAN NOT NULL DEFAULT false,
  "shortBio" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "PROVIDER_PROFILES_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "PROVIDER_CERTIFICATES" (
  "id" SERIAL NOT NULL,
  "providerId" INTEGER NOT NULL,
  "providerProfileId" INTEGER,
  "title" TEXT NOT NULL,
  "fileUrl" TEXT NOT NULL,
  "certificateType" TEXT NOT NULL,
  "verificationStatus" "CertificateVerificationStatus" NOT NULL DEFAULT 'PENDING',
  "rejectionReason" TEXT,
  "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "verifiedAt" TIMESTAMP(3),
  "verifiedByAdminId" INTEGER,

  CONSTRAINT "PROVIDER_CERTIFICATES_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "PROVIDER_PROFILES_userId_key" ON "PROVIDER_PROFILES"("userId");
CREATE INDEX "PROVIDER_PROFILES_district_idx" ON "PROVIDER_PROFILES"("district");
CREATE INDEX "PROVIDER_CERTIFICATES_providerId_uploadedAt_idx" ON "PROVIDER_CERTIFICATES"("providerId", "uploadedAt");
CREATE INDEX "PROVIDER_CERTIFICATES_verificationStatus_idx" ON "PROVIDER_CERTIFICATES"("verificationStatus");

ALTER TABLE "PROVIDER_PROFILES"
ADD CONSTRAINT "PROVIDER_PROFILES_userId_fkey"
FOREIGN KEY ("userId") REFERENCES "USERS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "PROVIDER_CERTIFICATES"
ADD CONSTRAINT "PROVIDER_CERTIFICATES_providerId_fkey"
FOREIGN KEY ("providerId") REFERENCES "USERS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "PROVIDER_CERTIFICATES"
ADD CONSTRAINT "PROVIDER_CERTIFICATES_providerProfileId_fkey"
FOREIGN KEY ("providerProfileId") REFERENCES "PROVIDER_PROFILES"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "PROVIDER_CERTIFICATES"
ADD CONSTRAINT "PROVIDER_CERTIFICATES_verifiedByAdminId_fkey"
FOREIGN KEY ("verifiedByAdminId") REFERENCES "USERS"("id") ON DELETE SET NULL ON UPDATE CASCADE;
