ALTER TABLE "TASKS"
ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "reviewedByAdminAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "reviewedByAdminId" INTEGER;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'PaymentLifecycleStatus') THEN
    CREATE TYPE "PaymentLifecycleStatus" AS ENUM ('PENDING', 'ESCROW_HELD', 'RELEASE_READY', 'RELEASED', 'FAILED', 'REFUNDED');
  END IF;
END $$;

ALTER TABLE "PAYMENT_TRANSACTIONS"
ADD COLUMN IF NOT EXISTS "totalAmount" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "escrowHeldAmount" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "platformFeeAmount" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "providerPayoutAmount" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "heldAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "releasedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lifecycleStatus" "PaymentLifecycleStatus" NOT NULL DEFAULT 'PENDING';
