-- AlterEnum
ALTER TYPE "TaskStatus" ADD VALUE 'PENDING_CONFIRMATION';

-- CreateTable
CREATE TABLE "TASK_PROGRESS_UPDATES" (
    "id" SERIAL NOT NULL,
    "progressPercent" INTEGER NOT NULL,
    "note" TEXT NOT NULL,
    "attachments" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "milestoneStatus" TEXT,
    "estimatedCompletionDate" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "taskId" INTEGER NOT NULL,
    "providerId" INTEGER NOT NULL,

    CONSTRAINT "TASK_PROGRESS_UPDATES_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TASK_PROGRESS_UPDATES_taskId_createdAt_idx" ON "TASK_PROGRESS_UPDATES"("taskId", "createdAt");

-- CreateIndex
CREATE INDEX "TASK_PROGRESS_UPDATES_providerId_idx" ON "TASK_PROGRESS_UPDATES"("providerId");

-- AddForeignKey
ALTER TABLE "TASK_PROGRESS_UPDATES" ADD CONSTRAINT "TASK_PROGRESS_UPDATES_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "TASKS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TASK_PROGRESS_UPDATES" ADD CONSTRAINT "TASK_PROGRESS_UPDATES_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "USERS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
